server:
  port: ${AUTH_PORT:8082}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

secret: ${JWT_SECRET}
cors:
  allowed-origin: ${ALLOWED_ORIGIN}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

jwt:
  expiration-ms: ${JWT_TIME:86400000}
refresh-token:
  ttl-days: ${REFRESH_TOKEN_TTL:2}