server:
  port: ${GATEWAY_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: 0
    timeout: 2000ms

secret: ${JWT_SECRET}
