# =========================
# Server Port
# =========================
server:
  port: ${GATEWAY_PORT}

# =========================
# Eureka Configuration
# =========================
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

# =========================
# Redis Configuration
# =========================
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# =========================
# JWT Secret
# =========================
secret: ${JWT_SECRET}
