# =========================
# General Configuration
# =========================
spring.application.name=auth
#server.port=${AUTH_PORT:8082}
server.port=${AUTH_PORT}
# =========================
# OAuth2 Configuration
# =========================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid, profile, email

# =========================
# Database Configuration
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# application.properties or application.yml
s

# =========================
# JWT Configuration
# =========================
secret=${JWT_SECRET}
# =========================
# Cloud Gateway (Disabled since no Eureka)
# =========================
spring.cloud.gateway.discovery.locator.enabled=false
#cors.allowed-origin=${CORS_ALLOWED_ORIGIN}
