spring.application.name=QUIZ-SERVICE

# ✅ Dynamic Server Configuration (Defaults to 8082)
#server.port=${QUIZ_PORT}
server.port=8083

# ✅ Database Configuration (Using Environment Variables with Defaults)
#spring.datasource.url=${DB_URL}
spring.datasource.url=jdbc:postgresql://localhost:5432/pokequizdb
spring.datasource.username=postgres
spring.datasource.password=Raunak@2005
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ✅ Hibernate Settings (Schema Validation)
spring.jpa.hibernate.ddl-auto=update

# ✅ Redis Configuration (Defaults to localhost
# ✅ Logging Configuration
logging.level.org.springframework=INFO
