spring.application.name=DEX-SERVICE

# ✅ Dynamic Server Configuration (Defaults to 8084)
#server.port=${DEX_PORT}
#
#
#
## ✅ Database Configuration (Using Environment Variables with Defaults)
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}
server.port=8084



# ✅ Database Configuration (Using Environment Variables with Defaults)
spring.datasource.url=jdbc:postgresql://localhost:5432/pokedexdb
spring.datasource.username=postgres
spring.datasource.password=Raunak@2005
spring.datasource.driver-class-name=org.postgresql.Driver

# ✅ Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
