spring.application.name=SCRIBBLE-SERVICE

# ✅ Dynamic Server Configuration (Defaults to 8085)
#server.port=${SCRIBBLE_PORT}
#
#
## ✅ Database Configuration (Using Environment Variables with Defaults)
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}
server.port=8085


# ✅ Database Configuration (Using Environment Variables with Defaults)
spring.datasource.url=jdbc:postgresql://localhost:5432/pokescribble
spring.datasource.username=postgres
spring.datasource.password=Raunak@2005
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ✅ Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
