spring:
  application:
    name: QUIZ-SERVICE
  profiles:
    active: ${QUIZ_PROFILE:dev}

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: INFO

